name: 'Brightspot Build'

on:
  workflow_call:
    inputs:
      build-maven:
        description: 'Build with Maven'
        default: false
        type: boolean

      build-gradle:
        description: 'Build with Gradle'
        default: true
        type: boolean

      gradle-params:
        description: 'Extra parameters to pass to Gradle command'
        required: false
        type: string

      gradle-action-cache-disable:
        description: 'Enable only if not using Gradle Remote Cache'
        required: false
        default: true
        type: boolean

      java-distribution:
        description: 'Java distribution'
        required: false
        default: 'temurin'
        type: string

      java-version:
        description: 'Java version'
        required: false
        default: '11'
        type: string

      node-version:
        description: 'Node version'
        required: false
        default: '16.11.0'
        type: string

      cache-npm:
        description: 'Cache NPM'
        default: true
        type: boolean

      war-build-dir:
        description: 'Directory containing the compiled WAR file. This overrides the default which is web/build/libs'
        required: false
        default: 'web/build/libs'
        type: string

      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-20.04-4core

      env1Name:
        description: Name for environment variable #1 (value is passed via secrets)
        type: string
      env2Name:
        description: Name for environment variable #2 (value is passed via secrets)
        type: string
      env3Name:
        description: Name for environment variable #3 (value is passed via secrets)
        type: string

    secrets:
      ENV_1_VALUE:
        required: false
      ENV_2_VALUE:
        required: false
      ENV_3_VALUE:
        required: false
      GRADLE_CACHE_USERNAME:
        required: false
      GRADLE_CACHE_PASSWORD:
        required: false

jobs:
  build:
    name: "Build"
    runs-on: ${{ inputs.runs-on }}
    # Map the job outputs to step outputs
    outputs:
      container-build-tag: ${{ steps.build-container.outputs.container-build-tag }}
      container-version-tag: ${{ steps.build-container.outputs.container-version-tag }}
    steps:
      - name: Set Environment Variables
        run: |
          if [ -n "${{ inputs.env1Name }}" ]; then
            echo "${{ inputs.env1Name }}=${{ secrets.ENV_1_VALUE }}" >> $GITHUB_ENV
          fi
          if [ -n "${{ inputs.env2Name }}" ]; then
            echo "${{ inputs.env2Name }}=${{ secrets.ENV_2_VALUE }}" >> $GITHUB_ENV
          fi
          if [ -n "${{ inputs.env3Name }}" ]; then
            echo "${{ inputs.env3Name }}=${{ secrets.ENV_3_VALUE }}" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4

        # must run before gradle/gradle-build-action
      - name: Validate Gradle wrapper JAR files
        if: ${{ inputs.build-gradle }}
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: ${{ inputs.node-version }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Gradle
        if: ${{ inputs.build-gradle }}
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.gradle-action-cache-disable }}

      - name: Get Tag Version
        shell: bash
        run: |
          echo "GITHUB_ACTIONS_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "GITHUB_ACTIONS_PULL_REQUEST=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: perfectsense/brightspot-github-actions-workflows
          ref: v2
          path: ./brightspot

      - name: Maven Cache
        if: ${{ inputs.build-maven }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: NPM Cache
        if: ${{ inputs.cache-npm}}
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.yarn/cache
            ~/.config/yarn/global
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build with Maven
        if: ${{ inputs.build-maven }}
        shell: bash
        run: ./brightspot/brightspot/build-maven.sh

      - name: Build with Gradle
        if: ${{ inputs.build-gradle }}
        shell: bash
        env:
          GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
          GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}
          GRADLE_PARAMS: ${{ inputs.gradle-params }}
        run: ./brightspot/brightspot/build-gradle.sh

      - name: Publish JUnit test reports
        uses: mikepenz/action-junit-report@v4
        if: ${{ inputs.build-gradle && !cancelled() }}
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Store Build
        if: ${{ inputs.build-gradle || inputs.build-maven }}
        uses: actions/upload-artifact@v4
        with:
            name: brightspot-build
            path: ${{ inputs.war-build-dir }}
            retention-days: 2

      - name: Find Brightspot Version
        if: ${{ inputs.build-gradle || inputs.build-maven }}
        run: ./brightspot/analysis/brightspot-version.sh > brightspot-version.txt
        shell: bash

      - name: Store Brightspot Version
        if: ${{ inputs.build-gradle || inputs.build-maven }}
        uses: actions/upload-artifact@v4
        with:
            name: brightspot-version
            path: brightspot-version.txt
            retention-days: 2

